"""
LPM model template generator.

Generates boilerplate code for new LPM models.
"""

from pathlib import Path
from textwrap import dedent

import click

LPM_MODEL_TEMPLATE = '''\
# -*- coding: utf-8 -*-
"""
LPM {class_name} distribution model.

Purpose
-------
Lumped Parameter Model using the {class_name} probability distribution
for groundwater age dating.

Author
------
[Your Name]
"""

from scipy.stats import {scipy_dist}

from pyage.LPM.core.{base_module} import {base_class}
from pyage.LPM.core.registry import register_lpm


@register_lpm("{name}")
class LPM_{name}({base_class}):
    """Lumped Parameter Model - {class_name} distribution.

    Parameters
    ----------
    mu : float
        Mean parameter (characteristic age in years).
    sigma : float
        Standard deviation parameter.
    directory_lpm : str, optional
        Directory for LPM parameter files.
    """

    scipy_dist = {scipy_dist}

    def __init__(self, mu=10.0, sigma=2.0, directory_lpm=None):
        """Initialize the {class_name} LPM.

        Parameters
        ----------
        mu : float
            Mean parameter (default: 10.0 years).
        sigma : float
            Standard deviation parameter (default: 2.0 years).
        directory_lpm : str, optional
            Directory for LPM parameter files.
        """
        parameter_values = {{"mu": mu, "sigma": sigma}}
        parameter_units = {{"mu": "year", "sigma": "year"}}
        super().__init__("{name}", parameter_values, parameter_units, directory_lpm)

    def _scipy_params(self):
        """Return scipy distribution parameters as (args, loc, scale).

        Returns
        -------
        tuple
            (args, loc, scale) for scipy.stats distribution methods.

        Notes
        -----
        Customize this method based on your chosen scipy distribution.

        Examples for common distributions:
        - Exponential: return (), 0, self.p["mu"]
        - Gamma: return (self.p["alpha"],), 0, self.p["beta"]
        - Inverse Gaussian: return (self.p["mu"],), 0, self.p["sigma"]
        - Normal: return (), self.p["mu"], self.p["sigma"]
        - Lognormal: return (self.p["sigma"],), 0, np.exp(self.p["mu"])
        """
        # TODO: Customize based on your distribution
        return (), self.p["mu"], self.p["sigma"]
'''

LPM_PARAMS_TEMPLATE = '''\
# LPM parameters for model "{name}"
#
# This YAML defines bounds, initial values, proposal steps, and priors
# for calibration routines (Simplex, Metropolis-Hastings).
#
# Generated by: pyage new lpm {name}

model: {name}
version: 1

parameters:
  - name: mu
    label: mean_age
    unit: year
    description: "Mean of the distribution (characteristic age)."
    bounds: [0.1, 100.0]
    init: 10.0
    step: 1.5
    prior:
      type: uniform
      min: 0.0
      max: 100.0
      unit: year

  - name: sigma
    label: std_age
    unit: year
    description: "Standard deviation parameter."
    bounds: [0.1, 50.0]
    init: 2.0
    step: 1.0
    prior:
      type: uniform
      min: 0.0
      max: 50.0
      unit: year

notes: |
  This is a template file. Customize the parameters based on your
  distribution's requirements.
'''


def generate_lpm_template(name: str, output: str | None, base: str) -> None:
    """Generate LPM model template files.

    Parameters
    ----------
    name : str
        Name identifier for the new LPM model.
    output : str or None
        Output directory for the model file. If None, uses default location.
    base : str
        Base class to extend: 'scipy', 'scipy_safe', or 'root'.
    """
    # Determine base class and module
    base_map = {
        "scipy": ("LPM_scipy", "LPMScipy", "norm"),
        "scipy_safe": ("LPM_scipy", "LPMScipySafe", "norm"),
        "root": ("LPM_root", "LPM", "norm"),
    }
    base_module, base_class, default_scipy = base_map[base]

    # Find repository root
    cli_dir = Path(__file__).resolve().parent.parent
    pyage_dir = cli_dir.parent
    repo_root = pyage_dir.parent

    # Default output location for model file
    if output is None:
        model_output = pyage_dir / "LPM" / "models"
    else:
        model_output = Path(output)

    model_output.mkdir(parents=True, exist_ok=True)

    # Generate class name from model name
    class_name = name.replace("_", " ").title().replace(" ", "")

    # Generate model file
    scipy_comment = "norm  # TODO: Replace with actual scipy.stats distribution"
    if base == "root":
        scipy_comment = "None  # Not used for root-based LPMs"

    model_content = LPM_MODEL_TEMPLATE.format(
        name=name,
        class_name=class_name,
        base_module=base_module,
        base_class=base_class,
        scipy_dist=scipy_comment,
    )

    model_file = model_output / f"LPM_{name}.py"

    if model_file.exists():
        if not click.confirm(f"File {model_file} already exists. Overwrite?"):
            click.echo("Aborted.")
            return

    model_file.write_text(model_content, encoding="utf-8")
    click.echo(click.style("Created:", fg="green") + f" {model_file}")

    # Generate params.yaml
    lpm_data_dir = repo_root / "data_core" / "data_LPM" / name
    lpm_data_dir.mkdir(parents=True, exist_ok=True)

    params_content = LPM_PARAMS_TEMPLATE.format(name=name)
    params_file = lpm_data_dir / "params.yaml"

    if params_file.exists():
        if not click.confirm(f"File {params_file} already exists. Overwrite?"):
            click.echo("Skipping params.yaml")
        else:
            params_file.write_text(params_content, encoding="utf-8")
            click.echo(click.style("Created:", fg="green") + f" {params_file}")
    else:
        params_file.write_text(params_content, encoding="utf-8")
        click.echo(click.style("Created:", fg="green") + f" {params_file}")

    # Show next steps
    click.echo()
    click.echo(click.style("Next steps:", fg="cyan", bold=True))
    click.echo(f"  1. Edit {model_file}")
    click.echo("     - Set the correct scipy_dist (e.g., norm, gamma, lognorm, invgauss)")
    click.echo("     - Update __init__ parameters if needed")
    click.echo("     - Implement _scipy_params() method for your distribution")
    click.echo(f"  2. Edit {params_file}")
    click.echo("     - Adjust parameter bounds, init values, and priors")
    click.echo(f"  3. Verify: pyage list lpms | grep {name}")
