# Copyright (c) 2021-2026 Centre national de la recherche scientifique (CNRS)
# Contributor: Jean-Raynald de Dreuzy
# SPDX-License-Identifier: CECILL-2.1
# This file generates configuration and recharge-data templates for a new tracer.

"""Create documented starter files for adding an environmental tracer.

The generated YAML shows where to declare units, valid dates, recharge history,
production, and radioactive decay. A companion tabular file demonstrates the
dated concentration columns accepted by the tracer loader.

These files are intentionally examples rather than fabricated scientific data:
developers must replace the placeholder metadata and chronicle values before the
tracer is suitable for convolution or calibration.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import click

TRACER_CONFIG_TEMPLATE = """\
# {name_upper} Tracer Configuration
#
# This file configures the {name} tracer for groundwater age dating.
#
# Generated by: pyages new tracer {name}
# Date: {date}

# =============================================================================
# Tracer Properties
# =============================================================================

# Unit of concentration measurement
# Common options: pptv, TU (Tritium Units), pmC (percent modern carbon), mol
unit: {unit}

# =============================================================================
# Recharge Configuration
# =============================================================================

# Enable recharge chronicle from external file
# If true, concentrations are loaded from recharge.csv in the same directory
# If false, use recharge_constant instead
recharge: {has_chronicle}

# Constant recharge concentration (only used if recharge: false)
{constant_line}

# =============================================================================
# Optional: Radioactive Decay
# =============================================================================

# Decay characteristic time in years (half-life / ln(2))
# Examples:
#   - Tritium (3H): 17.77 years (half-life 12.32 years)
#   - Carbon-14: 8267 years (half-life 5730 years)
#   - Krypton-85: 15.5 years (half-life 10.76 years)
{decay_line}

# =============================================================================
# Optional: Geoproduction
# =============================================================================

# In-situ production rate (concentration units per year)
# production_rate: 0.0

# =============================================================================
# Valid Date Range
# =============================================================================

# These are auto-determined from recharge.csv when recharge: true
# Only specify manually if recharge: false
{date_range}
"""

RECHARGE_CSV_TEMPLATE = """\
# =============================================================================
# {name_upper} Atmospheric Recharge Chronicle
# =============================================================================
#
# Tracer: {name}
# Unit: {unit}
#
# Data Source: [YOUR DATA SOURCE HERE]
# Reference: [CITATION]
#
# Temporal Coverage: {datemin} - {datemax}
# Generated: {date}
#
# Column Descriptions:
#   date: Decimal year (e.g., 2020.5 = July 1, 2020)
#   concentration: Atmospheric concentration in {unit}
#
# =============================================================================
date,concentration
{datemin},0.0
{middate1},0.5
{middate2},1.0
{middate3},0.8
{datemax},0.6
"""


def generate_tracer_template(
    name: str, output: str | None, with_chronicle: bool, with_decay: bool
) -> None:
    """Generate tracer template files.

    Parameters
    ----------
    name : str
        Name identifier for the new tracer.
    output : str or None
        Output directory. If None, uses default location.
    with_chronicle : bool
        If True, generate recharge.csv template.
    with_decay : bool
        If True, include radioactive decay configuration.
    """
    project_root = Path.cwd()

    # Default output location
    if output is None:
        tracer_output = project_root / "data_core" / "data_tracer"
    else:
        tracer_output = Path(output).resolve()

    tracer_dir = tracer_output / name
    tracer_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.now().strftime("%Y-%m-%d")

    # Default unit
    unit = "pptv"

    # Build configuration content
    config_content = TRACER_CONFIG_TEMPLATE.format(
        name=name,
        name_upper=name.upper(),
        date=today,
        unit=unit,
        has_chronicle="true" if with_chronicle else "false",
        constant_line=(
            "# recharge_constant: 1.0" if with_chronicle else "recharge_constant: 1.0"
        ),
        decay_line=(
            "half_life: 12.32  # Years; replace with the isotope's published half-life"
            if with_decay
            else "# half_life: 12.32"
        ),
        date_range=(
            "# datemin: 1940.0\n# datemax: 2025.0"
            if with_chronicle
            else "datemin: 1940.0\ndatemax: 2025.0"
        ),
    )

    # Write config file
    config_file = tracer_dir / f"{name}.yaml"

    if config_file.exists():
        if not click.confirm(f"File {config_file} already exists. Overwrite?"):
            click.echo("Aborted.")
            return

    config_file.write_text(config_content, encoding="utf-8")
    click.echo(click.style("Created:", fg="green") + f" {config_file}")

    # Generate recharge chronicle if requested
    if with_chronicle:
        csv_content = RECHARGE_CSV_TEMPLATE.format(
            name=name,
            name_upper=name.upper(),
            unit=unit,
            date=today,
            datemin="1950.0",
            middate1="1970.0",
            middate2="1990.0",
            middate3="2010.0",
            datemax="2025.0",
        )

        csv_file = tracer_dir / "recharge.csv"

        if csv_file.exists():
            if not click.confirm(f"File {csv_file} already exists. Overwrite?"):
                click.echo("Skipping recharge.csv")
            else:
                csv_file.write_text(csv_content, encoding="utf-8")
                click.echo(click.style("Created:", fg="green") + f" {csv_file}")
        else:
            csv_file.write_text(csv_content, encoding="utf-8")
            click.echo(click.style("Created:", fg="green") + f" {csv_file}")

    # Show next steps
    click.echo()
    click.echo(click.style("Next steps:", fg="cyan", bold=True))
    click.echo(f"  1. Edit {config_file}")
    click.echo("     - Set the correct unit for your tracer")
    if with_decay:
        click.echo("     - Adjust half_life for your specific isotope")
    if with_chronicle:
        click.echo(f"  2. Edit {tracer_dir / 'recharge.csv'}")
        click.echo("     - Replace placeholder data with actual atmospheric chronicle")
        click.echo("     - Add data source and citation")
    click.echo(f"  3. In workflow YAML, set tracers.data_directory to {tracer_output}")
    click.echo(f"  4. Verify by running a workflow that loads '{name}'")
