name: pyage
channels:
  - defaults
dependencies:
  - python
  - pandas
  - matplotlib
  - scipy
  - numpy
  - spyder
  - ipython
  - jupyter
  - imageio
  - ffmpeg
  - av
  - imageio-ffmpeg
  - pip
  - pip: 
    - empiricaldist
  