name: pyage
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - openpyxl
  - matplotlib
  - scipy
  - numpy
  - spyder
  - ipython
  - jupyter
  - imageio
  - ffmpeg
  - av
  - imageio-ffmpeg
  - pyyaml
  - pydantic
  - click
  - pytest
  - pip
  - pip:
    - empiricaldist
  
