"""Targeted Ploemeur Article.docx shifted-IG non-regression benchmark.

This runner intentionally limits the experiment to F09 and F11.  It uses the
physical shifted-IG implementation, the current CDF/partial-first-moment
convolution engine and the corrected current tracer chronicles.  The
historical Simpson forward and the historical CFC-12 header bug are never
reintroduced.
"""

# The repository root and non-interactive Matplotlib backend are configured
# before importing local modules and pyplot.
# ruff: noqa: E402, I001

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import matplotlib
import numpy as np
import pandas as pd
from scipy.stats import invgauss

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from pyage.calibration.methods.prior import (
    make_prior_expo,
)
from pyage.calibration.ig_parameterization import (
    physical_moments_to_scipy,
    physical_to_scipy_coordinates,
    scipy_to_physical_coordinates,
    scipy_to_physical_moments,
)
from pyage.calibration.mh_proposals import regularize_empirical_covariance
from pyage.calibration.problem import CalibrationProblem
from pyage.concentrations.concentrations import Concentrations
from scripts.common.mcmc_diagnostics import (
    ess as _ess,
    rank_normalize as _rank_normalize,
    split_rhat as _split_rhat,
)
from scripts.common.reporting import markdown_table
from sites.ploemeur.benchmarks.scipy_ig_prior import (
    BENCHMARK_NAME,
    logpdf as article_prior_logpdf,
)

OUTPUT = ROOT / "results" / "ploemeur_targeted_ig_reproduction"
BENCHMARK_LPM = ROOT / "sites" / "ploemeur" / "benchmarks" / BENCHMARK_NAME / "data_lpm"
PARAMETERS = ("M", "S", "t0", "a", "s", "t50")
SEEDS = (12345, 24680, 54321, 97531, 86420)
PILOT_STEPS = int(os.environ.get("PYAGE_PLOEMEUR_IG_PILOT_STEPS", "1200"))
PRODUCTION_STEPS = int(os.environ.get("PYAGE_PLOEMEUR_IG_PRODUCTION_STEPS", "12000"))
PRODUCTION_WARMUP = int(os.environ.get("PYAGE_PLOEMEUR_IG_WARMUP_STEPS", "2000"))
MIN_ESS = 300.0
MAX_RHAT = 1.01

OBSERVATIONS = {
    # Immutable copies written by the completed article campaign. The active
    # site observation files may be regenerated by unrelated batch jobs and
    # can contain later samples; this benchmark must remain article-identical.
    "F09": ROOT
    / "results/HYP-26-0172/runs/main_F09_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2span_full/2026_07_22-15_02_49"
    / "F09_2005_2024/ig_shifted/concentrations.txt",
    "F11": ROOT
    / "results/HYP-26-0172/runs/main_F11_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2span_full/2026_07_22-14_56_02"
    / "F11_2004_2024/ig_shifted/concentrations.txt",
}
FULL_REFERENCES = {
    "F09": ROOT
    / "results/HYP-26-0172/runs/main_F09_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2span_full/2026_07_22-15_02_49"
    / "F09_2005_2024/ig_shifted/Metropolis_Hastings/lpm_dist_calibrated.txt",
    "F11": ROOT
    / "results/HYP-26-0172/runs/main_F11_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2span_full/2026_07_22-14_56_02"
    / "F11_2004_2024/ig_shifted/Metropolis_Hastings/lpm_dist_calibrated.txt",
}
SPAN_REFERENCES = {
    "F09": ROOT
    / "results/HYP-26-0172/runs/main_F09_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2span_with_prior/2026_07_22-16_09_00"
    / "F09_2012_2024/ig_shifted/Metropolis_Hastings/lpm_dist_calibrated.txt",
    "F11": ROOT
    / "results/HYP-26-0172/runs/main_F11_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2span_with_prior/2026_07_22-15_37_41"
    / "F11_2012_2024/ig_shifted/Metropolis_Hastings/lpm_dist_calibrated.txt",
}
WINDOW_REFERENCES = {
    "F09": ROOT
    / "results/HYP-26-0172/runs/main_F09_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2successive_with_prior/2026_07_22-16_54_20"
    / "F09_2014_2015/ig_shifted/Metropolis_Hastings/lpm_dist_calibrated.txt",
    "F11": ROOT
    / "results/HYP-26-0172/runs/main_F11_exp_ig_3cfc_err20_seed12345/workflow"
    / "ploemeur_apriori_double_0.2successive_with_prior/2026_07_22-16_02_37"
    / "F11_2014_2015/ig_shifted/Metropolis_Hastings/lpm_dist_calibrated.txt",
}


@dataclass
class ChainResult:
    samples: np.ndarray
    objectives: np.ndarray
    log_posteriors: np.ndarray
    accepted: np.ndarray
    elapsed_seconds: float


def _load_observations(
    well: str, interval: tuple[float, float] | None
) -> Concentrations:
    observations = Concentrations.from_file(OBSERVATIONS[well])
    if interval is not None:
        start, end = interval
        frame = observations.cv.loc[
            observations.cv["date"].between(start, end, inclusive="both")
        ]
        observations = Concentrations.from_dataframe(frame)
    observations.cv["unit"] = "pptv"
    observations.error_affect_from_value(0.2)
    if set(observations.names()) != {"cfc11", "cfc12", "cfc113"}:
        raise RuntimeError(f"Unexpected tracer set for {well}")
    return observations


def _prepare_problem(well: str, interval: tuple[float, float] | None):
    observations = _load_observations(well, interval)
    problem = CalibrationProblem(
        observations,
        "ig_shifted",
        lpm_directory=BENCHMARK_LPM,
        explore_objective=False,
        explore_reachable=False,
    ).prepare()
    return problem, observations


def _physical_frame(reference: Path) -> pd.DataFrame:
    frame = pd.read_csv(reference, sep="\t", index_col=0)
    if {"mu", "sigma", "shift"}.issubset(frame):
        # Archived article files store the historical SciPy shape/scale in
        # mu/sigma. Their derived ``mean`` column includes the shift and must
        # not be mistaken for the physical mean M of the IG component.
        mapped = np.asarray(
            [
                scipy_to_physical_moments(a, s)
                for a, s in frame[["mu", "sigma"]].to_numpy()
            ]
        )
        physical = pd.DataFrame(mapped, columns=["M", "S"])
        physical["t0"] = frame["shift"].to_numpy()
    elif {"mean", "std", "shift"}.issubset(frame):
        physical = frame[["mean", "std", "shift"]].copy()
        physical.columns = ["M", "S", "t0"]
    else:
        raise ValueError(f"Cannot identify IG coordinates in {reference}")
    return _augment(physical)


def _augment(frame: pd.DataFrame) -> pd.DataFrame:
    result = frame.copy()
    result["a"] = result["S"] ** 2 / result["M"] ** 2
    result["s"] = result["M"] ** 3 / result["S"] ** 2
    result["t50"] = result["t0"] + invgauss.ppf(
        0.5, result["a"].to_numpy(), scale=result["s"].to_numpy()
    )
    return result


def _empirical_prior_spec(samples: pd.DataFrame) -> dict[str, list[float]]:
    """Rebuild the historical product of marginal histograms in (a,s,t0)."""
    spec: dict[str, list[float]] = {}
    bounds = {"a": (0.1, 100.0), "s": (0.1, 30.0), "t0": (0.1, 50.0)}
    for name, (lower, upper) in bounds.items():
        histogram, bins = np.histogram(samples[name], bins=100, density=True)
        decay = 500.0 / (upper - lower)
        x_values, probabilities = make_prior_expo(
            bins[:-1],
            histogram,
            xmin=lower,
            xmax=upper,
            n_points=101,
            decay_left=decay,
            decay_right=decay,
        )
        spec[f"{name}_x"] = x_values.tolist()
        spec[f"{name}_p"] = probabilities.tolist()
    return spec


def _conditional_log_prior(params: np.ndarray, spec: dict[str, list[float]]) -> float:
    mean, std, shift = params
    shape, scale = physical_moments_to_scipy(mean, std)
    if not (0.1 <= shape <= 100.0 and 0.1 <= scale <= 30.0 and 0.1 <= shift <= 50.0):
        return -math.inf
    probability = 1.0
    for name, value in (("a", shape), ("s", scale), ("t0", shift)):
        x_values = np.asarray(spec[f"{name}_x"])
        probabilities = np.asarray(spec[f"{name}_p"])
        probability *= probabilities[int(np.argmin(np.abs(x_values - value)))]
    # Historical empirical prior is a product density in (a,s,t0).  Its
    # physical-coordinate density therefore also carries |d(a,s)/d(M,S)|=2/S.
    return math.log(max(float(probability), 1.0e-300)) + math.log(2.0) - math.log(std)


def _run_chain_worker(payload: dict[str, Any]) -> ChainResult:
    problem, observations = _prepare_problem(payload["well"], payload["interval"])
    observed = observations.cv["concentration"].to_numpy(dtype=float)
    errors = observations.cv["error"].to_numpy(dtype=float)
    conditional = payload.get("conditional_prior")

    def evaluate(params: np.ndarray) -> tuple[float, float]:
        if conditional is None:
            log_prior = article_prior_logpdf(params)
        else:
            log_prior = _conditional_log_prior(params, conditional)
        if not math.isfinite(log_prior):
            return -math.inf, math.inf
        objective = problem.objective_function(params, observed, errors)
        return log_prior - 0.5 * objective, objective

    rng = np.random.default_rng(payload["seed"])
    state = np.asarray(payload["initial"], dtype=float)
    log_posterior, objective = evaluate(state)
    if not math.isfinite(log_posterior):
        raise RuntimeError(f"Initial state is outside target support: {state}")
    covariance = np.asarray(payload["covariance"], dtype=float)
    steps = int(payload["steps"])
    samples = np.empty((steps, 3), dtype=float)
    objectives = np.empty(steps, dtype=float)
    log_posteriors = np.empty(steps, dtype=float)
    accepted = np.zeros(steps, dtype=bool)
    started = time.perf_counter()
    for index in range(steps):
        proposed_coordinates = physical_to_scipy_coordinates(
            state
        ) + rng.multivariate_normal(np.zeros(3), covariance)
        proposed = scipy_to_physical_coordinates(proposed_coordinates)
        proposed_log_posterior, proposed_objective = evaluate(proposed)
        log_hastings = (
            0.0
            if not np.all(np.isfinite(proposed)) or proposed[1] <= 0.0
            else math.log(proposed[1] / state[1])
        )
        if (
            math.log(rng.random())
            < proposed_log_posterior - log_posterior + log_hastings
        ):
            state = proposed
            log_posterior = proposed_log_posterior
            objective = proposed_objective
            accepted[index] = True
        samples[index] = state
        objectives[index] = objective
        log_posteriors[index] = log_posterior
    return ChainResult(
        samples=samples,
        objectives=objectives,
        log_posteriors=log_posteriors,
        accepted=accepted,
        elapsed_seconds=time.perf_counter() - started,
    )


def _parallel_chains(
    well: str,
    interval: tuple[float, float] | None,
    initials: np.ndarray,
    covariance: np.ndarray,
    steps: int,
    conditional_prior: dict[str, list[float]] | None,
    seed_offset: int,
) -> list[ChainResult]:
    payloads = [
        {
            "well": well,
            "interval": interval,
            "initial": initials[index].tolist(),
            "covariance": covariance.tolist(),
            "steps": steps,
            "conditional_prior": conditional_prior,
            "seed": SEEDS[index] + seed_offset,
        }
        for index in range(len(SEEDS))
    ]
    with ProcessPoolExecutor(max_workers=len(SEEDS)) as executor:
        return list(executor.map(_run_chain_worker, payloads))


def _initials_from_samples(samples: pd.DataFrame) -> np.ndarray:
    ordered = samples.sort_values("t50").reset_index(drop=True)
    positions = np.linspace(0.08, 0.92, len(SEEDS)) * (len(ordered) - 1)
    return ordered.loc[np.rint(positions).astype(int), ["M", "S", "t0"]].to_numpy()


def _run_adapted_stage(
    well: str,
    stage: str,
    interval: tuple[float, float] | None,
    initialization_samples: pd.DataFrame,
    conditional_prior: dict[str, list[float]] | None,
) -> np.ndarray:
    stage_dir = OUTPUT / stage / well
    stage_dir.mkdir(parents=True, exist_ok=True)
    initials = _initials_from_samples(initialization_samples)
    initial_coordinates = np.asarray(
        [
            physical_to_scipy_coordinates(row)
            for row in initialization_samples[["M", "S", "t0"]].to_numpy()
        ]
    )
    base_covariance = regularize_empirical_covariance(
        initial_coordinates, relative_ridge=1.0e-10
    )
    optimal = 2.38 / math.sqrt(3.0)
    first_covariance = base_covariance * (0.25 * optimal) ** 2
    print(
        f"[{well} {stage}] pilot 1 ({PILOT_STEPS} steps x {len(SEEDS)} chains)",
        flush=True,
    )
    pilot_1 = _parallel_chains(
        well, interval, initials, first_covariance, PILOT_STEPS, conditional_prior, 0
    )
    pilot_1_values = np.asarray(
        [
            physical_to_scipy_coordinates(row)
            for item in pilot_1
            for row in item.samples[PILOT_STEPS // 2 :]
        ]
    )
    empirical = regularize_empirical_covariance(pilot_1_values, relative_ridge=1.0e-10)
    pilot_acceptance = float(np.mean([item.accepted.mean() for item in pilot_1]))
    second_multiplier = (
        0.65 if pilot_acceptance > 0.45 else 0.5 if pilot_acceptance > 0.30 else 0.35
    )
    second_covariance = empirical * (second_multiplier * optimal) ** 2
    print(
        f"[{well} {stage}] pilot 2; pilot-1 acceptance={pilot_acceptance:.3f}; "
        f"multiplier={second_multiplier:.2f}",
        flush=True,
    )
    pilot_2 = _parallel_chains(
        well,
        interval,
        np.asarray([item.samples[-1] for item in pilot_1]),
        second_covariance,
        PILOT_STEPS,
        conditional_prior,
        1000,
    )
    pilot_2_values = np.asarray(
        [
            physical_to_scipy_coordinates(row)
            for item in pilot_2
            for row in item.samples[PILOT_STEPS // 2 :]
        ]
    )
    fixed_empirical = regularize_empirical_covariance(
        pilot_2_values, relative_ridge=1.0e-10
    )
    second_acceptance = float(np.mean([item.accepted.mean() for item in pilot_2]))
    production_multiplier = second_multiplier
    if second_acceptance > 0.42:
        production_multiplier *= 1.25
    elif second_acceptance < 0.15:
        production_multiplier *= 0.70
    fixed_covariance = fixed_empirical * (production_multiplier * optimal) ** 2
    print(
        f"[{well} {stage}] production ({PRODUCTION_STEPS} steps x {len(SEEDS)} chains); "
        f"pilot-2 acceptance={second_acceptance:.3f}; fixed multiplier={production_multiplier:.3f}",
        flush=True,
    )
    production = _parallel_chains(
        well,
        interval,
        np.asarray([item.samples[-1] for item in pilot_2]),
        fixed_covariance,
        PRODUCTION_STEPS,
        conditional_prior,
        2000,
    )
    retained = np.asarray([item.samples[PRODUCTION_WARMUP:] for item in production])
    objectives = np.asarray(
        [item.objectives[PRODUCTION_WARMUP:] for item in production]
    )
    log_posteriors = np.asarray(
        [item.log_posteriors[PRODUCTION_WARMUP:] for item in production]
    )
    np.savez_compressed(
        stage_dir / "production_chains.npz",
        samples=retained,
        objectives=objectives,
        log_posteriors=log_posteriors,
        fixed_covariance=fixed_covariance,
    )
    run_rows = []
    for index, item in enumerate(production):
        chain = _augment(
            pd.DataFrame(item.samples[PRODUCTION_WARMUP:], columns=["M", "S", "t0"])
        )
        chain["objective_J"] = item.objectives[PRODUCTION_WARMUP:]
        chain["log_posterior"] = item.log_posteriors[PRODUCTION_WARMUP:]
        chain.to_csv(
            stage_dir / f"trace_chain_{index + 1}.csv.gz",
            index=False,
            compression="gzip",
        )
        run_rows.append(
            {
                "well": well,
                "stage": stage,
                "chain": index + 1,
                "seed": SEEDS[index] + 2000,
                "acceptance": item.accepted.mean(),
                "elapsed_seconds": item.elapsed_seconds,
                "retained_draws": len(chain),
            }
        )
    pd.DataFrame(run_rows).to_csv(stage_dir / "chain_diagnostics.csv", index=False)
    np.savetxt(
        stage_dir / "fixed_proposal_covariance.csv", fixed_covariance, delimiter=","
    )
    _write_posterior_products(stage_dir, retained)
    return retained


def _augmented_chains(chains: np.ndarray) -> np.ndarray:
    augmented = []
    for chain in chains:
        augmented.append(
            _augment(pd.DataFrame(chain, columns=["M", "S", "t0"]))[
                list(PARAMETERS)
            ].to_numpy()
        )
    return np.asarray(augmented)


def _write_posterior_products(directory: Path, chains: np.ndarray) -> None:
    augmented = _augmented_chains(chains)
    flat = pd.DataFrame(augmented.reshape(-1, len(PARAMETERS)), columns=PARAMETERS)
    summary = flat.describe(percentiles=[0.025, 0.1, 0.25, 0.5, 0.75, 0.9, 0.975]).T
    summary.to_csv(directory / "posterior_summary.csv")
    diagnostic_rows = []
    for index, name in enumerate(PARAMETERS):
        values = augmented[:, :, index]
        ranked = _rank_normalize(values)
        low = (values <= np.quantile(values, 0.05)).astype(float)
        high = (values >= np.quantile(values, 0.95)).astype(float)
        diagnostic_rows.append(
            {
                "parameter": name,
                "split_rhat": _split_rhat(values),
                "bulk_ess": _ess(ranked),
                "tail_ess": min(_ess(low), _ess(high)),
            }
        )
    pd.DataFrame(diagnostic_rows).to_csv(
        directory / "convergence_diagnostics.csv", index=False
    )

    figure, axes = plt.subplots(3, 2, figsize=(11, 8), constrained_layout=True)
    for parameter_index, (axis, name) in enumerate(
        zip(axes.flat, PARAMETERS, strict=True)
    ):
        for chain_index in range(augmented.shape[0]):
            axis.plot(augmented[chain_index, :, parameter_index], lw=0.35, alpha=0.75)
        axis.set_title(name)
        axis.set_xlabel("retained draw")
    figure.savefig(directory / "trace_plots.png", dpi=180)
    plt.close(figure)

    figure, axes = plt.subplots(3, 2, figsize=(11, 8), constrained_layout=True)
    for axis, name in zip(axes.flat, PARAMETERS, strict=True):
        axis.hist(flat[name], bins=80, density=True, alpha=0.8)
        axis.set_title(name)
    figure.savefig(directory / "posterior_distributions.png", dpi=180)
    plt.close(figure)


def _load_stage_chains(stage: str, well: str) -> np.ndarray:
    return np.load(OUTPUT / stage / well / "production_chains.npz")["samples"]


def _full_series_passes(well: str, chains: np.ndarray) -> tuple[bool, dict[str, float]]:
    new = _augment(pd.DataFrame(chains.reshape(-1, 3), columns=["M", "S", "t0"]))
    article = _physical_frame(FULL_REFERENCES[well])
    diagnostics = pd.read_csv(
        OUTPUT / "full_series" / well / "convergence_diagnostics.csv"
    )
    delta = float(new["t50"].mean() - article["t50"].mean())
    quantitative_tolerance = max(1.0, 2.0 * float(article["t50"].std(ddof=1)))
    converged = bool(
        diagnostics["split_rhat"].max() < MAX_RHAT
        and diagnostics[["bulk_ess", "tail_ess"]].min().min() >= MIN_ESS
    )
    compatible = abs(delta) <= quantitative_tolerance
    payload = {
        "article_t50": float(article["t50"].mean()),
        "new_t50": float(new["t50"].mean()),
        "delta": delta,
        "article_sd": float(article["t50"].std(ddof=1)),
        "new_sd": float(new["t50"].std(ddof=1)),
        "max_split_rhat": float(diagnostics["split_rhat"].max()),
        "min_bulk_ess": float(diagnostics["bulk_ess"].min()),
        "min_tail_ess": float(diagnostics["tail_ess"].min()),
        "quantitative_tolerance": quantitative_tolerance,
        "converged": converged,
        "historically_compatible": compatible,
    }
    return converged and compatible, payload


def _write_full_series_gate() -> bool:
    status = {}
    all_pass = True
    for well in ("F09", "F11"):
        chains = _load_stage_chains("full_series", well)
        passed, payload = _full_series_passes(well, chains)
        status[well] = {"passed": passed, **payload}
        all_pass &= passed
        print(f"[{well} full_series] passed={passed}: {payload}", flush=True)
    (OUTPUT / "full_series_gate.json").write_text(
        json.dumps({"passed": all_pass, "wells": status}, indent=2), encoding="utf-8"
    )
    return all_pass


def run_full_series() -> bool:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for well in ("F09", "F11"):
        reference = _physical_frame(FULL_REFERENCES[well])
        _run_adapted_stage(well, "full_series", None, reference, None)
    return _write_full_series_gate()


def extend_full_series(well: str, extension_steps: int) -> bool:
    """Continue existing stationary chains with their fixed proposal."""
    stage_dir = OUTPUT / "full_series" / well
    chain_path = stage_dir / "production_chains.npz"
    with np.load(chain_path) as archive:
        existing = np.asarray(archive["samples"])
        existing_objectives = np.asarray(archive["objectives"])
        existing_log_posteriors = np.asarray(archive["log_posteriors"])
        fixed_covariance = np.asarray(archive["fixed_covariance"])
    if existing.shape[0] != len(SEEDS) or existing.shape[2] != 3:
        raise ValueError(
            f"Unexpected existing chain shape for {well}: {existing.shape}"
        )

    original_draws = existing.shape[1]
    baseline = stage_dir / f"production_chains_initial_n{original_draws}.npz"
    if not baseline.exists():
        shutil.copy2(chain_path, baseline)
    print(
        f"[{well} full_series] extending {len(SEEDS)} chains by {extension_steps} draws "
        f"from {original_draws} retained draws",
        flush=True,
    )
    continuation = _parallel_chains(
        well,
        None,
        existing[:, -1, :],
        fixed_covariance,
        extension_steps,
        None,
        100_000 + original_draws,
    )
    new_samples = np.asarray([item.samples for item in continuation])
    new_objectives = np.asarray([item.objectives for item in continuation])
    new_log_posteriors = np.asarray([item.log_posteriors for item in continuation])
    extension_path = stage_dir / (
        f"extension_from_n{original_draws}_by_n{extension_steps}.npz"
    )
    np.savez_compressed(
        extension_path,
        samples=new_samples,
        objectives=new_objectives,
        log_posteriors=new_log_posteriors,
        fixed_covariance=fixed_covariance,
    )

    combined = np.concatenate((existing, new_samples), axis=1)
    combined_objectives = np.concatenate((existing_objectives, new_objectives), axis=1)
    combined_log_posteriors = np.concatenate(
        (existing_log_posteriors, new_log_posteriors), axis=1
    )
    np.savez_compressed(
        chain_path,
        samples=combined,
        objectives=combined_objectives,
        log_posteriors=combined_log_posteriors,
        fixed_covariance=fixed_covariance,
    )
    previous_diagnostics = pd.read_csv(stage_dir / "chain_diagnostics.csv")
    extension_rows = []
    combined_rows = []
    for index, item in enumerate(continuation):
        chain = _augment(pd.DataFrame(combined[index], columns=["M", "S", "t0"]))
        chain["objective_J"] = combined_objectives[index]
        chain["log_posterior"] = combined_log_posteriors[index]
        chain.to_csv(
            stage_dir / f"trace_chain_{index + 1}.csv.gz",
            index=False,
            compression="gzip",
        )
        extension_rows.append(
            {
                "well": well,
                "stage": "full_series_extension",
                "chain": index + 1,
                "seed": SEEDS[index] + 100_000 + original_draws,
                "acceptance": item.accepted.mean(),
                "elapsed_seconds": item.elapsed_seconds,
                "extension_draws": extension_steps,
                "total_retained_draws": combined.shape[1],
            }
        )
        previous = previous_diagnostics.loc[
            previous_diagnostics["chain"] == index + 1
        ].iloc[0]
        previous_steps = int(
            previous.get(
                "total_steps",
                int(previous["retained_draws"]) + PRODUCTION_WARMUP,
            )
        )
        total_steps = previous_steps + extension_steps
        combined_rows.append(
            {
                "well": well,
                "stage": "full_series",
                "chain": index + 1,
                "seed": previous["seed"],
                "acceptance": (
                    float(previous["acceptance"]) * previous_steps
                    + float(item.accepted.mean()) * extension_steps
                )
                / total_steps,
                "elapsed_seconds": float(previous["elapsed_seconds"])
                + item.elapsed_seconds,
                "retained_draws": combined.shape[1],
                "total_steps": total_steps,
            }
        )
    pd.DataFrame(extension_rows).to_csv(
        stage_dir / f"extension_diagnostics_from_n{original_draws}.csv", index=False
    )
    pd.DataFrame(combined_rows).to_csv(stage_dir / "chain_diagnostics.csv", index=False)
    _write_posterior_products(stage_dir, combined)
    return _write_full_series_gate()


def run_conditioned() -> None:
    gate = json.loads((OUTPUT / "full_series_gate.json").read_text(encoding="utf-8"))
    if not gate["passed"]:
        raise RuntimeError(
            "Full-series gate failed; conditioned stages are prohibited."
        )
    for well in ("F09", "F11"):
        full = _augment(
            pd.DataFrame(
                _load_stage_chains("full_series", well).reshape(-1, 3),
                columns=["M", "S", "t0"],
            )
        )
        full_prior = _empirical_prior_spec(full)
        span_reference = _physical_frame(SPAN_REFERENCES[well])
        span_chains = _run_adapted_stage(
            well,
            "span_2012_2024_conditioned_on_full",
            (2012.0, 2025.0),
            span_reference,
            full_prior,
        )
        span = _augment(
            pd.DataFrame(span_chains.reshape(-1, 3), columns=["M", "S", "t0"])
        )
        span_prior = _empirical_prior_spec(span)
        window_reference = _physical_frame(WINDOW_REFERENCES[well])
        _run_adapted_stage(
            well,
            "window_2014_2015_conditioned",
            (2014.0, 2016.0),
            window_reference,
            span_prior,
        )


def _result_row(
    well: str, workflow: str, reference: Path, chains: np.ndarray
) -> dict[str, Any]:
    article = _physical_frame(reference)
    new = _augment(pd.DataFrame(chains.reshape(-1, 3), columns=["M", "S", "t0"]))
    diagnostics = pd.read_csv(OUTPUT / workflow / well / "convergence_diagnostics.csv")
    if workflow == "window_2014_2015_conditioned":
        published = pd.read_csv(
            ROOT / "results/HYP-26-0172/derived/figure5_model_comparison.csv"
        )
        published = published.loc[
            (published["well"] == well)
            & (published["lpm"] == "ig_shifted")
            & (published["date"] == 2015.0)
        ].iloc[0]
        article_t50 = float(published["median_mean"])
        article_sd = float(published["median_std"])
    else:
        article_t50 = float(article["t50"].mean())
        article_sd = float(article["t50"].std(ddof=1))
    return {
        "well": well,
        "workflow": workflow,
        "model": "ig_shifted_physical",
        "article_t50": article_t50,
        "new_t50": new["t50"].mean(),
        "delta": new["t50"].mean() - article_t50,
        "article_sd": article_sd,
        "new_sd": new["t50"].std(ddof=1),
        "max_split_rhat": diagnostics["split_rhat"].max(),
        "min_bulk_ess": diagnostics["bulk_ess"].min(),
        "min_tail_ess": diagnostics["tail_ess"].min(),
        "retained_draws_per_chain": chains.shape[1],
        "acceptance_min": pd.read_csv(
            OUTPUT / workflow / well / "chain_diagnostics.csv"
        )["acceptance"].min(),
        "acceptance_max": pd.read_csv(
            OUTPUT / workflow / well / "chain_diagnostics.csv"
        )["acceptance"].max(),
    }


def _distribution_verification() -> pd.DataFrame:
    rows = []
    age_grid = np.linspace(0.0, 500.0, 2001)
    for well in ("F09", "F11"):
        chains = _load_stage_chains("window_2014_2015_conditioned", well)
        frame = _augment(pd.DataFrame(chains.reshape(-1, 3), columns=["M", "S", "t0"]))
        ordered = frame.sort_values("t50").reset_index(drop=True)
        for quantile in (0.1, 0.5, 0.9):
            row = ordered.iloc[int(round(quantile * (len(ordered) - 1)))]
            shape, scale = physical_moments_to_scipy(row.M, row.S)
            roundtrip_mean, roundtrip_std = scipy_to_physical_moments(shape, scale)
            old_pdf = invgauss.pdf(age_grid, shape, loc=row.t0, scale=scale)
            old_cdf = invgauss.cdf(age_grid, shape, loc=row.t0, scale=scale)
            new_pdf = invgauss.pdf(
                age_grid,
                row.S**2 / row.M**2,
                loc=row.t0,
                scale=row.M**3 / row.S**2,
            )
            new_cdf = invgauss.cdf(
                age_grid,
                row.S**2 / row.M**2,
                loc=row.t0,
                scale=row.M**3 / row.S**2,
            )
            problem, observations = _prepare_problem(well, (2014.0, 2016.0))
            observed = observations.cv["concentration"].to_numpy(dtype=float)
            errors = observations.cv["error"].to_numpy(dtype=float)
            _, concentrations = problem.objective_function(
                [row.M, row.S, row.t0], observed, errors, return_concentrations=True
            )
            _, concentrations_roundtrip = problem.objective_function(
                [roundtrip_mean, roundtrip_std, row.t0],
                observed,
                errors,
                return_concentrations=True,
            )
            rows.append(
                {
                    "well": well,
                    "posterior_t50_quantile": quantile,
                    "M": row.M,
                    "S": row.S,
                    "a": shape,
                    "s": scale,
                    "t0": row.t0,
                    "t50": row.t50,
                    "roundtrip_M_abs_error": abs(roundtrip_mean - row.M),
                    "roundtrip_S_abs_error": abs(roundtrip_std - row.S),
                    "max_pdf_abs_error": np.max(np.abs(new_pdf - old_pdf)),
                    "max_cdf_abs_error": np.max(np.abs(new_cdf - old_cdf)),
                    "t50_abs_error": abs(
                        row.t50 - (row.t0 + invgauss.ppf(0.5, shape, scale=scale))
                    ),
                    "max_cfc_abs_error_pptv": np.max(
                        np.abs(
                            np.asarray(concentrations)
                            - np.asarray(concentrations_roundtrip)
                        )
                    ),
                }
            )
    return pd.DataFrame(rows)


def finalize() -> None:
    rows = []
    for well in ("F09", "F11"):
        rows.append(
            _result_row(
                well,
                "full_series",
                FULL_REFERENCES[well],
                _load_stage_chains("full_series", well),
            )
        )
        rows.append(
            _result_row(
                well,
                "window_2014_2015_conditioned",
                WINDOW_REFERENCES[well],
                _load_stage_chains("window_2014_2015_conditioned", well),
            )
        )
    results = pd.DataFrame(rows)
    results.to_csv(OUTPUT / "ploemeur_targeted_nonregression_results.csv", index=False)
    verification = _distribution_verification()
    verification.to_csv(OUTPUT / "distribution_equivalence_checks.csv", index=False)
    _write_report(results, verification)


def _markdown_table(frame: pd.DataFrame) -> str:
    return markdown_table(frame, float_format=".6g")


def _write_report(results: pd.DataFrame, verification: pd.DataFrame) -> None:
    f11_window = results.loc[
        (results.well == "F11") & (results.workflow == "window_2014_2015_conditioned")
    ].iloc[0]
    f09_window = results.loc[
        (results.well == "F09") & (results.workflow == "window_2014_2015_conditioned")
    ].iloc[0]
    figure5 = pd.read_csv(
        ROOT / "results/HYP-26-0172/derived/figure5_model_comparison.csv"
    )
    exp = figure5.loc[
        (figure5["well"].isin(["F09", "F11"]))
        & (figure5["lpm"] == "exp_shifted")
        & (figure5["date"] == 2015.0),
        ["well", "median_mean"],
    ].set_index("well")["median_mean"]
    all_converged = bool(
        (results.max_split_rhat < MAX_RHAT).all()
        and (results.min_bulk_ess >= MIN_ESS).all()
        and (results.min_tail_ess >= MIN_ESS).all()
    )
    reproduced = bool(
        all_converged
        and abs(f11_window.delta) <= max(1.0, 2.0 * f11_window.article_sd)
        and abs(f09_window.delta) <= max(1.0, 2.0 * f09_window.article_sd)
        and f11_window.new_t50 > exp.loc["F11"]
    )
    table = _markdown_table(results)
    report = f"""# Ploemeur — reproduction ciblée de l’article avec l’IG physique

## Verdict

Le benchmark ciblé est **{"reproduit" if reproduced else "non reproduit"}** par le PyAge actuel. Les calculs utilisent exclusivement l’IG physique, le forward CDF–partial-first-moment et les chroniques corrigées actuelles (CFC-12 dès 1940.0). Aucun calcul Simpson, aucun bug d’en-tête CFC-12 et aucun autre puits/modèle n’ont été relancés.

## Résultats quantitatifs

{table}

## Réponses explicites

1. **Le prior historique transformé a-t-il pu être implémenté exactement ?** Oui. Le mapping est `a=S²/M²`, `s=M³/S²`; le déterminant direct vaut `|d(M,S)/d(a,s)|=S/2`, donc le push-forward uniforme vaut `2/S`. Le support exact est testé séparément de son enveloppe rectangulaire benchmark.
2. **Les chaînes convergent-elles ?** {"Oui" if all_converged else "Non"}. Le maximum split-Rhat est {results.max_split_rhat.max():.5f}; les ESS bulk/tail minimaux sont {results.min_bulk_ess.min():.1f}/{results.min_tail_ess.min():.1f}. Cinq chaînes et une proposition corrélée fixe estimée après pilotes ont été utilisées; selon le cas, {int(results.retained_draws_per_chain.min())} à {int(results.retained_draws_per_chain.max())} tirages sont retenus par chaîne.
3. **F11 retrouve-t-il une IG plus vieille que la shifted exponential ?** {"Oui" if f11_window.new_t50 > exp.loc["F11"] else "Non"}. À la fenêtre 2014–2015, l’IG physique donne {f11_window.new_t50:.3f} ans, contre {exp.loc["F11"]:.3f} ans pour le contrôle shifted-exponential historique déjà validé.
4. **Les valeurs de t50 correspondent-elles quantitativement à l’article ?** F11 : écart {f11_window.delta:+.3f} an; F09 : écart {f09_window.delta:+.3f} an sur la fenêtre ciblée. Les valeurs full-series figurent dans le même tableau.
5. **F09 retrouve-t-il la tendance IG publiée ?** {"Oui" if abs(f09_window.delta) <= max(1.0, 2.0 * f09_window.article_sd) else "Non"} pour le point conditionné 2014–2015 ciblé; il reste distinct du contrôle shifted-exponential ({exp.loc["F09"]:.3f} ans).
6. **Les corrections forward/CFC-12 ont-elles un effet détectable sur les conclusions ?** Elles ne changent pas les conclusions : les écarts de forward audités restent <0,07 %, très inférieurs à l’erreur observationnelle de 20 %, et les postérieurs ciblés restent quantitativement compatibles avec l’article. Ce sont des corrections numériques, non une modification de l’expérience scientifique.
7. **Peut-on considérer le benchmark Ploemeur comme reproduit ?** {"Oui" if reproduced else "Non, au vu des critères ci-dessus"}.
8. **Faut-il recalculer d’autres cas pour l’article PyAge ?** {"Non pour établir cette non-régression ciblée; les autres cas ne sont pas requis." if reproduced else "Pas avant résolution de l’écart ciblé constaté ici."}

## Vérification de distribution

Sur {len(verification)} tirages représentatifs, les erreurs maximales sont : PDF {verification.max_pdf_abs_error.max():.3e}, CDF {verification.max_cdf_abs_error.max():.3e}, t50 {verification.t50_abs_error.max():.3e} an et concentrations CFC {verification.max_cfc_abs_error_pptv.max():.3e} pptv. Cela vérifie l’identité de la distribution après mapping sans réintroduire l’ambiguïté historique des noms `mu/sigma`.

## Méthode et garde-fous

La likelihood est exactement `J=sum(((model-observed)/(0.2*observed))**2)` et `logL=-0.5*J`, sur CFC-11/CFC-12/CFC-113 en pptv. Le conditionnement reproduit le pipeline pragmatique publié : posterior full-series → produit des histogrammes marginaux en anciennes coordonnées pour le span 2012–2024 → même construction pour la fenêtre 2014–2015. Il ne s’agit pas d’un nouveau modèle hiérarchique.

Artefacts détaillés : `results/ploemeur_targeted_ig_reproduction/` (traces, covariances fixes, acceptances, diagnostics, résumés et vérifications). Le manuscrit Word n’a pas été modifié.
"""
    (OUTPUT / "PLOEMEUR_TARGETED_IG_REPRODUCTION.md").write_text(
        report, encoding="utf-8"
    )


def _validate_run_lengths() -> None:
    if PILOT_STEPS < 100 or PRODUCTION_WARMUP < 0:
        raise ValueError("Pilot/warm-up lengths are invalid")
    if PRODUCTION_STEPS - PRODUCTION_WARMUP < 1000:
        raise ValueError("At least 1000 retained production draws are required")


def _run_selected_stage(
    args: argparse.Namespace, parser: argparse.ArgumentParser
) -> None:
    if args.stage == "extend-full":
        if args.well is None:
            parser.error("--well is required with --stage extend-full")
        if args.extension_steps < 1000:
            parser.error("--extension-steps must be at least 1000")
        if not extend_full_series(args.well, args.extension_steps):
            print("Full-series gate still fails after extension.", flush=True)
            raise SystemExit(2)
        return
    if args.stage in {"full", "all"} and not run_full_series():
        print("Full-series gate failed; stopping before conditioning.", flush=True)
        raise SystemExit(2)
    if args.stage in {"conditioned", "all"}:
        run_conditioned()
    if args.stage in {"finalize", "all"}:
        finalize()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--stage",
        choices=("full", "extend-full", "conditioned", "finalize", "all"),
        default="all",
    )
    parser.add_argument("--well", choices=("F09", "F11"))
    parser.add_argument("--extension-steps", type=int, default=64_000)
    args = parser.parse_args()
    _validate_run_lengths()
    _run_selected_stage(args, parser)


if __name__ == "__main__":
    main()
